name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install --workspaces
      - name: Build web package
        run: npm run build -w @awale/web
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: packages/web/dist
