name: Deploy GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm install --workspaces
      - name: Build web
        run: npm run build -w @awale/web
      - name: Prepare site
        run: |
          mkdir site
          cp -r packages/web/dist/* site/
          # Copy .htaccess for cache control
          if [ -f packages/web/public/.htaccess ]; then cp packages/web/public/.htaccess site/; fi
          # Basic index fallback if needed
          if [ ! -f site/index.html ]; then echo '<!doctype html><title>Awale</title><h1>Build Missing</h1>' > site/index.html; fi
          # SPA fallback and disable Jekyll
          cp site/index.html site/404.html
          touch site/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
