name: Release Assets

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm install --workspaces
      - name: Build web
        run: npm run build -w @awale/web
      - name: Archive dist
        run: |
          cd packages/web/dist
          zip -r ../../web-dist.zip .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/web/web-dist.zip
          generate_release_notes: true
